apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wireguard-config
  labels:
    {{- include "wireguard-socat.labels" . | nindent 4 }}
data:
  default.conf: |-
    [Interface]
    PrivateKey = {{ .Values.wireguard.privateKey }}
    Address = {{ .Values.wireguard.address }}
    PostUp = /socat.sh
    PreDown = kill -9 $(ps x | grep "socat" | grep -v grep | awk '{ print $1 }')

    [Peer]
    PublicKey = {{ .Values.wireguard.peer.publicKey }}
    AllowedIPs = {{ .Values.wireguard.peer.allowedIPs }}
    Endpoint = {{ .Values.wireguard.peer.endpoint }}
    PersistentKeepalive = {{ .Values.wireguard.peer.persistentKeepalive }}